#!/sbin/runscript
# Copyright 2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/dev-util/subversion/files/svnserve.initd,v 1.2 2005/08/25 13:59:48 pauldv Exp $

depend() {
	need net
}

start() {
	local my_opts="${PEDRO_OPTS}"
	[ "${PEDRO_PORT}" != "" ] && my_opts="-P${PEDRO_PORT} ${my_opts}"

	ebegin "Starting Pedro"
	start-stop-daemon --start --quiet --background --make-pidfile \
		--pidfile /var/run/pedro.pid --exec /usr/bin/pedro \
		-- ${my_opts}
	eend $?
}

stop() {
	ebegin "Stopping Pedro"
	start-stop-daemon --stop --quiet --pidfile /var/run/pedro.pid
	eend $?
}
